# Managed by mail-server install.sh
clamav {
  scan_mime_parts = true;
  scan_text_mime = false;
  scan_image_mime = false;
  symbol = "CLAM_VIRUS";
  type = "clamav";
  action = "reject";
  message = "Rejected: virus found ${VIRUS}";
  log_clean = false;
  servers = "/run/clamav/clamd.ctl";
}
